# Generated by Django 5.1 on 2024-11-28 05:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app7', '0002_recipe'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='image_name',
            field=models.ImageField(blank=True, null=True, upload_to='img/'),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='title',
            field=models.CharField(max_length=100),
        ),
    ]
